name: Run Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - run: pip install pytest requests

      - run: pytest test_main.py -v --junit-xml=results.xml
        if: always()

      - name: Test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: pytest results
          path: results.xml
          reporter: java-junit